webapps/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth.views import LogoutView
from intro2mc import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/<str:endpoint>', views.api, name='api'),
    path('', views.home, name='home'),
    path('syllabus/', views.syllabus, name='syllabus'),
    path('server-map/', views.map, name='map'),
    path('student-portal', views.account, name='account'),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(template_name="index.html"), name='logout'),
    path('attendance/', views.attendance, name='attendance'),
    path('excuse/', views.excuse, name='excuse'),
    path('invite/', views.invite, name='invite'),
    path('assignments/', views.assignments, name='assignments'),
    path('records/', views.records, name='records'),
    path('registration', views.register_ign, name='registration'),
    path('toggle-admin', views.toggle_admin, name='toggleadmin'),
    path('admin-panel/', views.admin_panel, name="adminpanel"),
    path('admin-panel/<str:action>', views.admin_panel, name="adminpanel-action"),
    path('404', views.page_not_found, name='404')
]

handler404 = 'intro2mc.views.page_not_found'

intro2mc/models.py
from django.db import models

######## Web app settings ########
# Adapted from https://www.rootstrap.com/blog/simple-dynamic-settings-for-django/
class Singleton(models.Model):

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(Singleton, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, _ = cls.objects.get_or_create(pk=1)
        return obj
        
class AppConfig(Singleton):
    id = models.AutoField(primary_key=True)
    currSemester = models.CharField(max_length=200)
    syllabus = models.CharField(max_length=200)
    serverMapURL = models.CharField(max_length=200)
    serverAddress = models.CharField(max_length=200)
    # All andrew ids on the roster, separated by ','
    roster = models.TextField(blank=True)

class HasTimeStamps(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

######## Attendance ########
class Student(HasTimeStamps):
    andrewID = models.CharField(max_length=200, primary_key=True)
    name = models.CharField(max_length=200, default='')
    picture = models.CharField(max_length=200)
    IGN = models.CharField(max_length=200)
    discord = models.CharField(max_length=200)
    uuid = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.andrewID} [{self.IGN}] ({self.discord})'

class InvitedStudent(HasTimeStamps):
    IGN = models.CharField(max_length=200, primary_key=True)
    uuid = models.CharField(max_length=200)
    invitedBy = models.ForeignKey(Student, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.IGN)

class ClassSession(HasTimeStamps):
    date = models.DateField(primary_key=True)
    code = models.CharField(max_length=200)
    term = models.CharField(max_length=200)
    accepting = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.term}-{self.date}'

class Attendance(HasTimeStamps):
    id = models.AutoField(primary_key=True)
    student = models.ForeignKey(Student, on_delete=models.PROTECT)
    term = models.CharField(max_length=200)
    classSession = models.ForeignKey(ClassSession, on_delete=models.PROTECT)
    excused = models.BooleanField(default=False)
    reason = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f'{self.student} {self.classSession}'

######## Website contents ########
class Video(HasTimeStamps):
    videoURL = models.CharField(max_length=200, primary_key=True)
    description = models.TextField(blank=True)

class Meme(HasTimeStamps):
    imageURL = models.CharField(max_length=200, primary_key=True)
    description = models.TextField(blank=True)

class Resource(HasTimeStamps):
    id = models.AutoField(primary_key=True)
    URL = models.CharField(max_length=200)
    imageURL = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

######## Assignments ########
class Assignment(HasTimeStamps):
    id = models.AutoField(primary_key=True)
    term = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    userSubmittable = models.BooleanField(default=False)
    gradeReleased = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.term}-{self.name}'

class Submission(HasTimeStamps):
    id = models.AutoField(primary_key=True)
    assignment = models.ForeignKey(Assignment, on_delete=models.PROTECT)
    student = models.ForeignKey(Student, on_delete=models.PROTECT)
    details = models.TextField(blank=True)
    grade = models.CharField(max_length=1, default='U')

    def __str__(self):
        return f'{self.assignment}-{self.student}'

intro2mc/forms.py
from django import forms
import intro2mc.models as models
import re

class AppCfgForm(forms.ModelForm):
    class Meta:
        model = models.AppConfig
        fields = '__all__'
        labels = {
            'currSemester': 'Semester'
        }
    
    def clean_roster(self):
        data = self.cleaned_data['roster'].lower()
        roster = set(re.findall(r'\w+', data))
        return ','.join(roster)
   
    def clean_currSemester(self):
        return self.cleaned_data['currSemester'].lower()

class StudentForm(forms.ModelForm):
    class Meta:
        model = models.Student
        fields = ['IGN', 'discord']
    
    def clean_IGN(self):
        ign = self.cleaned_data['IGN']
        if len(ign) > 16:
            raise forms.ValidationError("IGNs cannot exceed 16 characters")
        if not re.match("^[\w]+$", ign):
            raise forms.ValidationError("Illegal characters detected. Only a-z, A-Z, 0-9 and _ are allowed.")
        return ign

class ExcuseForm(forms.ModelForm):
    class Meta:
        model = models.Attendance
        fields = ['student', 'classSession', 'reason']
        widgets = {
            'student': forms.Select(attrs={'class': 'form-control'}),
            'classSession': forms.Select(attrs={'class': 'form-control'}),
            'reason': forms.TextInput(attrs={'class': 'form-control bg-white'})
        }

class InviteForm(forms.ModelForm):
    class Meta:
        model = models.InvitedStudent
        fields = ['IGN', 'invitedBy']
        widgets = {
            'IGN': forms.TextInput(attrs={'class': 'form-control bg-white'}),
            'invitedBy': forms.Select(attrs={'class': 'form-control'})
        }

    def clean_IGN(self):
        ign = self.cleaned_data['IGN']
        if len(ign) > 16:
            raise forms.ValidationError("IGNs cannot exceed 16 characters")
        if not re.match("^[\w]+$", ign):
            raise forms.ValidationError("Illegal characters detected. Only a-z, A-Z, 0-9 and _ are allowed.")
        return ign

intro2mc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as UserModel
from django.contrib.auth import logout
from django.core.cache import cache
from django.contrib import messages
from django.utils import timezone
from django.conf import settings
from django.http import HttpResponseForbidden, HttpResponseNotFound, HttpResponse

from mcstatus import MinecraftServer
import requests
import logging
import uuid
import json
import string
import random
import datetime

from intro2mc.alerts import *
from intro2mc.forms import *
from intro2mc.models import *

GOOGLE_DISCOVERY_URL = (
    "https://accounts.google.com/.well-known/openid-configuration"
)
USERINFO_ENDPOINT_KEY = "userinfo_endpoint"

STATUS_NO_CONTENT = 204

logger = logging.getLogger(__name__)

def home(request):
    context = get_default_context()
    context['user'] = request.user
    if 'error' in request.session:
        messages.error(request, request.session["error"])
        del request.session["error"]
    
    context['videos'] = Video.objects.all()

    messages.info(request, 'This website is still in development. Let us know if you found any bugs')

    return render(request, 'index.html', context)

@login_required()
def register_ign(request):
    context = get_default_context()
    try:
        student = Student.objects.get(andrewID=request.user.username)
        form = StudentForm(instance=student)
    except Exception as e:
        try:
            userinfo = fetch_userinfo(request)
            student = Student(
                andrewID=userinfo["andrew_id"],
                name=userinfo["first_name"],
                picture=userinfo["picture"],
            )
            form = StudentForm()
        except Exception as e:
            logout(request)
            messages.error(request, authencication_failed_err('Something went wrong, please log in again.'))
            return redirect('home')

    context["student"] = student
    context['form'] = form
    if request.method == 'POST':           
        form = StudentForm(request.POST)

        if not form.is_valid():
            context['form'] = form
            return render(request, 'registration.html', context)

        try:
            case_correct_username, id = fetch_mojang_userinfo(form.cleaned_data["IGN"])
        except Exception as e:
            messages.error(request, f'Error fetching uuid for {form.cleaned_data["IGN"]}. Try clicking the Submit button again. If it still does not work, it is usually means that you entered a nonexistent username.')
            return render(request, 'registration.html', context)
        else:
            student.uuid = str(uuid.UUID(id))
            student.IGN = case_correct_username
            student.discord = form.cleaned_data["discord"]
            student.save()

            messages.success(request, 'You have been successfully registered.')
            return redirect('account')

    return render(request, 'registration.html', context)

@login_required
def invite(request):
    context = get_default_context()
    if not request.user.is_superuser:
        messages.error(request, access_denied_err())
        return redirect('home')
    cfg = AppConfig().load()

    if request.method == 'POST':
        form = InviteForm(request.POST)
        if form.is_valid():
            try:
                case_correct_username, uid = fetch_mojang_userinfo(form.cleaned_data["IGN"])
            except Exception as e:
                messages.error(request, f'Error fetching uuid for {form.cleaned_data["IGN"]}. Try clicking the Submit button again. If it still does not work, it is usually means that you entered a nonexistent username.')
            else:
                invited, created = InvitedStudent.objects.get_or_create(
                    IGN=case_correct_username,
                    uuid=str(uuid.UUID(uid)),
                    invitedBy=form.cleaned_data['invitedBy']
                )
                if created:
                    invited.save()
                    messages.success(request, f'{case_correct_username} has been successfully whitelisted.')
                else:
                    messages.warning(request, f'{case_correct_username} has already been invited by {form.invitedBy}.')
        context['form'] = form
    else:
        context['form'] = InviteForm()

    context['invited_students'] = []
    for s in InvitedStudent.objects.all().order_by('-created_at'):
        context['invited_students'].append(s)
    return render(request, 'invite.html', context)

def page_not_found(request, exception=None):
    messages.error(request, "This page does not exist.")
    return redirect('home')

def syllabus(request):
    cfg = AppConfig().load()
    if cfg.syllabus is not None and cfg.syllabus != '':
        return redirect(cfg.syllabus)
    return redirect('home')

@login_required()
def map(request):
    cfg = AppConfig().load()
    if cfg.serverMapURL is not None and cfg.serverMapURL != '':
        return redirect(cfg.serverMapURL)
    return redirect('home')

@login_required()
def account(request):
    context = get_default_context()
    if request.user.is_superuser:
        return redirect('adminpanel')

    try: student = Student.objects.get(andrewID=request.user.username)
    except Exception as e:
        return redirect('registration')

    cfg = AppConfig().load()

    try:
        server = MinecraftServer.lookup(cfg.serverAddress)
        status = server.status()
        players = status.players.online
    except Exception as e:
        print(e)
        players = None

    context['student'] = student
    context['server'] = {
        'address': cfg.serverAddress,
        'players': players,
    }
    return render(request, 'account.html', context)

@login_required()
def attendance(request):
    context = get_default_context()
    cfg = AppConfig().load()

    if request.user.is_superuser:
        sessions = ClassSession.objects.filter(term=cfg.currSemester).order_by('date')
        classes = []
        for s in sessions:
            classes.append(s)

        context["classes"] = classes
        return render(request, 'attendance.html', context)

    try:
        student = Student.objects.get(andrewID=request.user.username)
    except Exception as e:
        messages.error(request, generic_err("Unable to find student.", e))
        return redirect('registration')

    if request.method == 'POST':
        try:
            sess = ClassSession.objects.get(code=request.POST.get("code").upper(), term=cfg.currSemester, accepting=True)
            attendance, created = Attendance.objects.get_or_create(
                student=student,
                term=cfg.currSemester,
                classSession=sess
            )
            if created:
                attendance.save()
                messages.success(request, 'Your attendance has been recorded.')
            else:
                messages.warning(request, 'You have already signed in.')
        except Exception as e:
            messages.error(request, authencication_failed_err("Invalid or expired attendance code."))

    sessions = ClassSession.objects.filter(term=cfg.currSemester).order_by('date')
    classes = []
    absences = 0
    for s in sessions:
        cls = {'date': str(s.date)}
        try:
            att = Attendance.objects.get(student=student, term=cfg.currSemester, classSession=s)
            if att.excused: cls['status'] = 'Excused'
            else: cls['status'] = 'Present'
        except Exception as e:
            if s.date < timezone.localtime(student.created_at).date(): cls['status'] = 'N/A'
            else:
                cls['status'] = 'Absent'
                absences += 1
        classes.append(cls)

    context = {
        'student': student,
        'classes': classes,
        'absences': absences,
    }

    return render(request, 'attendance.html', context)

@login_required
def excuse(request):
    context = get_default_context()
    if not request.user.is_superuser:
        messages.error(request, access_denied_err())
        return redirect('home')
    cfg = AppConfig().load()

    if request.method == 'POST':
        try:
            stu = Student.objects.get(andrewID=request.POST['student'])
            sess = ClassSession.objects.get(date=request.POST['classSession'])
            att, created = Attendance.objects.get_or_create(
                student=stu,
                term=cfg.currSemester,
                classSession=sess
            )
            att.reason = request.POST['reason']
            att.excused = True
            att.save()
            if created:
                messages.success(request, 'Student excused.')
            else:
                messages.success(request, 'Attendance updated.')
        except Exception as e:
            messages.error(request, generic_err("Unable to find student or class session.", e))

    context['form'] = ExcuseForm()
    context['excused_absences'] = []
    for att in Attendance.objects.filter(excused=True).order_by('-updated_at'):
        d = {}
        d['date'] = att.updated_at
        d['session'] = att.classSession.date
        d['student'] = att.student
        d['reason'] = att.reason
        context['excused_absences'].append(d)
    return render(request, 'excuse.html', context)

@login_required
def records(request):
    context = get_default_context()
    if not request.user.is_superuser:
        messages.error(request, access_denied_err())
        return redirect('home')
    cfg = AppConfig().load()

    # Get relevant student, class, and assignment objects
    assignments = Assignment.objects.filter(term=cfg.currSemester).order_by('created_at')
    classes = ClassSession.objects.filter(term=cfg.currSemester).order_by('date')
    students = Student.objects.all().order_by('andrewID')

    ### Attendance ###
    # header row of table
    dates = []
    for c in classes:

intro2mc/templates/account.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Student Portal
{% endblock %}

{% block script %}
    <script>
        function copy() {
            navigator.clipboard.writeText("{{ server.address }}")
        }
        $(document).ready(function(){
            $('.popover-dismiss').popover({
                trigger: 'focus'
            })
            $('[data-toggle="popover"]').popover()
        });
    </script>
{% endblock %}

{% block style %}
    <style>
        i:hover {
            cursor: pointer;
            color: black !important;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="text-center m-3 p-3 bg-light content-box">
        <div class="h3 p-3">My Profile</div>
        <div class="p-3">
            <img src="{{ student.picture }}" alt="">
            <div class="h4 my-1">{{ student.name }}</div>
            <div class="text-muted">
                Andrew ID: <span class="font-weight-bold">{{ student.andrewID }}</span>
            </div>
            <div class="text-muted">
                IGN: <span class="font-weight-bold">{{ student.IGN }}</span>
                <a href="{% url 'registration' %}" class="ml-1">edit</a>
            </div>
        </div>
        <div class="row mb-3 justify-content-center">
            <div class="col-md-5 col-8">
                <a href="{% url 'attendance' %}" 
                   role="button" 
                   class="btn btn-primary btn-block my-2">
                   Attendance
                </a>
                <a href="{% url 'assignments' %}" 
                   role="button" 
                   class="btn btn-primary btn-block my-2">
                   Assignments
                </a>
                <a href="{% url 'logout' %}" 
                   role="button" 
                   class="btn btn-outline-secondary btn-block my-2">
                   Log out
                </a>
            </div>
        </div>
    </div>
    {% if server %}
        <div class="text-center m-3 p-3 bg-light content-box">
            <div class="h3 p-3">Server Details</div>
            <div class="pb-3">
                <div class="h5">IP Address</div>
                <div>
                    {{ server.address }} 
                    <a class="ml-2" tabindex="0" id="copy" data-trigger="focus" onClick="copy()" data-toggle="popover" data-content="Copied to clipboard!">
                        <i class="far fa-copy text-muted"></i>
                    </a>
                </div>
            </div>
            <div class="pb-3">
                <div class="h5">Status</div>
                {% if server.players != None %}
                    <div class="text-success text-uppercase font-weight-bold">running</div>
                    <div class="text-muted">{{ server.players }} player{% if server.players > 1 %}s{% endif %} online</div>
                {% else %}
                    <div class="text-danger text-uppercase font-weight-bold">offline</div>
                    <div class="text-muted">We might be running server maintenance. Please try again later. Contact us if this issue persists.</div>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}

intro2mc/templates/attendance.html
{% extends "base.html" %}
{% load static %}
{% load template_filters %}

{% block title %}
    Attendance
{% endblock %}

{% block script %}
    {% csrf_token %}
    <script type="text/javascript">
        $(document).ready(function(){
            $(function () {
                $('[data-toggle="tooltip"]').tooltip();
            })
        })

        {% if user.is_superuser %}
            function rerollcode(date) {
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function() {
                    if (xhr.readyState == XMLHttpRequest.DONE) {
                        if (xhr.status == 200) {
                            document.getElementById("id_"+date).innerHTML = xhr.responseText;
                        } else {
                            alert("Something went wrong.");
                        }
                    }
                }
                xhr.open("POST", "https://mcstuco.net/api/rerollcode");
                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.send("date=" + date);
            }

            function togglesession(date, action) {
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function() {
                    if (xhr.readyState == XMLHttpRequest.DONE) {
                        if (xhr.status == 200) {
                            if (action == "open") {
                                document.getElementById("id_opened_"+date).removeAttribute("hidden");
                                document.getElementById("id_closed_"+date).setAttribute("hidden", "hidden");
                            } else {
                                document.getElementById("id_opened_"+date).setAttribute("hidden", "hidden");
                                document.getElementById("id_closed_"+date).removeAttribute("hidden");
                            }
                        } else {
                            alert("Something went wrong.");
                        }
                    }
                }
                xhr.open("POST", "https://mcstuco.net/api/togglesession");
                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.send("date=" + date + "&action=" + action);
            }

            function newsession() {
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function() {
                    if (xhr.readyState == XMLHttpRequest.DONE) {
                        if (xhr.status == 200) {
                            location.reload();
                        } else {
                            alert("Something went wrong.");
                        }
                    }
                }
                xhr.open("POST", "https://mcstuco.net/api/newsession");
                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.send();
            }

            function deletesession(date) {
                if (!confirm("Do you really want to delete the class session on "+date+"?")) return;
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function() {
                    if (xhr.readyState == XMLHttpRequest.DONE) {
                        if (xhr.status == 200) {
                            location.reload();
                        } else {
                            alert("Something went wrong.");
                        }
                    }
                }
                xhr.open("POST", "https://mcstuco.net/api/deletesession");
                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.send("date=" + date);
            }
        {% endif %}
    </script>
{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        <div class="m-3 text-left">
            <a class="btn btn-link" onclick="history.back()">
                <i class="fas fa-angle-left"></i> Back
            </a>
        </div>
        <div class="text-center m-3 p-3 bg-light content-box">
            <div class="container">
                <div class="row p-3">
                    <div class="col-md-6 offset-md-3 h3 justify-content-center">Class sessions</div>
                    <div class="col-md-3 justify-content-end"><button class="btn btn-outline-primary" onclick="newsession()">+ New session</button></div>
                </div>
            </div>
            <table class="table" style='white-space:nowrap'>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Code</th>
                        <th>Accepting (click to toggle)</th>
                        <th>Delete session</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in classes %}
                        <tr>
                            <th>{{ c.date }}</th>
                            <td>
                                <span id="id_{{ c.date }}">{{ c.code }}</span>
                                <button class="btn btn-info fas fa-redo-alt text-light" onclick="rerollcode('{{ c.date }}')"/>
                            </td>
                            <td>
                                <button id="id_opened_{{ c.date }}"
                                        class="btn btn-primary"
                                        onclick="togglesession('{{ c.date }}', 'close')"
                                        {% if not c.accepting %}hidden="hidden"{% endif %}>Opened</button>
                                <button id="id_closed_{{ c.date }}"
                                        class="btn btn-danger"
                                        onclick="togglesession('{{ c.date }}', 'open')"
                                        {% if c.accepting %}hidden="hidden"{% endif %}>Closed</button>
                            </td>
                            <td>
                                <span class="btn btn-link fas fa-trash-alt" onclick="deletesession('{{ c.date }}')"></span>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="m-3 text-left">
            <a class="btn btn-link" href="{% url 'account' %}" >
                <i class="fas fa-angle-left"></i> Back
            </a>
        </div>
        <div class="text-center m-3 p-3 bg-light content-box">
            <div class="h5 p-3">Attendance Records for <span class="font-weight-bold">{{ student.andrewID }}</span></div>
            <form action="{% url 'attendance' %}" method="post" class="my-4">
                {% csrf_token %}
                <div class="d-inline-flex justify-content-center">
                    <input type="text" class="form-control w-10 bg-white"
                        name="code"
                        id="id_code"
                        placeholder="Attendance code"
                        autofocus onClick="this.select();">

                    <button type="submit" class="btn btn-primary mx-2">Submit</button>
                </div>
            </form>
            <div class="m-3">
                {% if classes|length == 0 %}
                    <div class="text-muted">
                        Nothing to show here
                    </div>
                {% else %}
                    <div class="table-responsive">
                        <table class="table" style='white-space:nowrap'>
                            <thead>
                                <tr>
                                    <th scope="col">Class</th>
                                    {% for c in classes %}
                                        <th scope="col">{{ c.date }}</td>
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">Status</th>
                                    {% for c in classes %}
                                        <td scope="row">
                                            <i class="{{ c.status|get_attendance_faclass }}" data-toggle="tooltip" title="{{ c.status }}"></i>
                                        </td>
                                    {% endfor %}
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="text-left text-muted">You have {{ absences }} unexcused absence{% if absences > 1 or absences == 0 %}s{% endif %}*</div>
                {% endif %}
            </div>
        </div>
        <div class="text-muted font-weight-light m-4 text-left">
            * As per StuCo 
            <u><a class="text-muted" href="https://www.cmu.edu/stuco/faq/" target="_blank">policy</a></u>,
            you will be given a no pass grade if you have more than 
            <span class="font-weight-bold">two</span> 
            unexcused absences. Make sure to contact us if you can't make it to class!
        </div>
    {% endif %}
{% endblock %}

intro2mc/templates/semester.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Admin Panel
{% endblock %}

{% block content %}
    <form action="{% url 'adminpanel-action' action='semester' %}" method="post">
        <table>
            {{form}}
        </table>
        {% csrf_token %}
        <button type="submit">Submit</button>
        <a href="{% url 'adminpanel' %}">Cancel</a>
    </form>
{% endblock %}